apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-upload
  labels:
    app: webapp-upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-upload
  template:
    metadata:
      name: webapp-upload
      labels:
        app: webapp-upload
    spec:
      containers:
        - name: webapp-upload
          image: dimmaryanto93/training-nke-webapp-upload:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
            limits:
              memory: 500Mi
              cpu: 1000m
          volumeMounts:
            - mountPath: /var/data/upload
              name: data-upload
      restartPolicy: Always
      volumes:
        - name: data-upload
          persistentVolumeClaim:
            claimName: pvc-ntnx-files-upload
