apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ntnx-files-upload
spec:
  storageClassName: ntnx-files-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem