apiVersion: v1
kind: Service
metadata:
  name: webapp-upload
spec:
  selector:
    app: webapp-upload
    tier: dev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort