apiVersion: v1
kind: Service
metadata:
  name: webapp-net
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.12.1.90
spec:
  selector:
    app: webapp-net
    tier: dev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer