apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ntnx-files-upload
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  volumeName: pv-ntnx-files-upload