apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ntnx-files-upload
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /logging
    server: 10.55.22.48