apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: webapp-upload
  labels:
    app: webapp-upload
    tier: dev
spec:
  serviceName: webapp-upload
  selector:
    matchLabels:
      app: webapp-upload
      tier: dev
  template:
    spec:
      containers:
        - name: webapp-upload
          image: dimmaryanto93/training-nke-webapp-upload:v1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
            limits:
              memory: 500Mi
              cpu: 1000m
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data-uploader
              mountPath: /var/data/upload
      restartPolicy: Always
  volumeClaimTemplates:
    - spec:
        volumeName: data-uploader
        volumeMode: Filesystem
        storageClassName: ntnx-files-sc
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 20Gi
